name: Build HMCL executable file with plugin loader

on: [ workflow_dispatch ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout Plugin Loader
        uses: actions/checkout@v4

      - name: Checkout HMCLauncher
        uses: actions/checkout@v4
        with:
          repository: HMCL-dev/HMCL
          sparse-checkout: |
            /HMCLauncher/
          path: HMCL

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x86

      - name: Apply patch
        run: |
          cd HMCL
          git apply --stat ..\patch\javaagent.patch
          git apply --check ..\patch\javaagent.patch
          git apply ..\patch\javaagent.patch
          Get-Content -Path HMCLauncher\HMCL\main.cpp

      - name: Build HMCLauncher
        run: msbuild /p:Configuration=Release /t:Rebuild /verbosity:detailed .\HMCL\HMCLauncher\

      - name: Copy HMCLauncher to assets
        run: |
          
          Copy-Item .\HMCL\HMCLauncher\Release\HMCLauncher.exe -Destination .\HMCL\src\main\resources\assets\HMCLauncher.exe

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
          java-package: 'jdk+fx'

      - name: Build with Gradle
        run: .\gradlew makeExecutables --no-daemon

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: HMCLPluginLoader
          path: build/dist
