name: Build HMCL plugin loader executable

on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Plugin Loader
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
          java-package: 'jdk+fx'

      - name: Set gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew makeExecutables --no-daemon

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: HMCLPluginLoader
          path: loader/build/libs